
class AllocableItemTemplateLocators {

    ALLOCABLE_ITEM_TEMPLATE = "//a[contains(text(), ' Allocable Item Templates ')]";
    ADD_ALLOCABLE_TEMPLATE = "//div[@class='trux-button__content']//span[contains(text(),'Add Template')]"
    ALLOCABLE_TEMPLATE_NAME = "//trux-input[@formcontrolname='name']"
    ALLOCABLE_TEMPLATE_DESCRIPTION = "//trux-input[@formcontrolname='description']"
    ALLOCABLE_TAX_YEAR_DROPDOWN = "(//trux-input[@formcontrolname='taxYear'])[2]"
    SELECT_ALLOCABLE_TAX_YEAR = "//li[contains(text(),'2023')]"
    SAVE_BUTTON = "//div[contains(text(),' Save ')]"
    VERIFY_DEFAULT_STANDARD_DESCRIPTION_MAPPING = "(//span[contains(text(),'Line 1 | Gain on Sale of Assets - Capital')])[1]"
    VERIFY_DEFAULT_STANDARD_DESCRIPTION_NEGATIVE_MAPPING = "(//span[contains(text(),'Line 1 | Excise and Stamp Taxes Expense')])[1]"
    STANDARD_DESCRIPTION_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='3']//span)[1]"
    STANDARD_DESCRIPTION_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='3']//div//div//div//input)[1]"
    SELECT_STANDARD_DESCRIPTION= "//div[contains(text(),'Line 1 | Incentive Compensation')]"
    ALLOCABLE_PAGE_CLICK = "//div[@class='engagement-settings-taxonomy-templates-page']"
    CLIPBOARD_ICON = "//tr[@aria-rowindex='3']//td[@aria-colindex='4']//fa-icon[@class='ng-fa-icon']"
    CLIPBOARD_ICON_2 = "//tr[@aria-rowindex='3']//td[@aria-colindex='5']//fa-icon[@class='ng-fa-icon']"
    STANDARD_DESCRIPTION_NEGATIVE_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//span)[1]"
    STANDARD_DESCRIPTION_NEGATIVE_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//div//div//div//input)[1]"
    SELECT_STANDARD_DESCRIPTION_NEGATIVE  = "//div[contains(text(),'Line 1 | Warranty Expense')]"
    ALLOCABLE_TEMPLATE_STATE = "//a[contains(text(),' State ')]"
    FEDERAL_STANDARD_DESCRIPTION_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//span)[1]"
    FEDERAL_STANDARD_DESCRIPTION_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//div//div//div//input)[1]"
    SELECT_FEDERAL_STANDARD_DESCRIPTION = "//div[contains(text(),'Line 1 | Abandonments')]"
    FEDERAL_STANDARD_DESCRIPTION_NEGATIVE_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='5']//span)[1]"
    FEDERAL_STANDARD_DESCRIPTION_NEGATIVE_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='5']//div//div//div//input)[1]"
    SELECT_FEDERAL_STANDARD_DESCRIPTION_NEGATIVE = "//div[contains(text(),'Line 1 | Lobbying Expenses')]"
    SAVE_PROFILE = "//span[contains(text(),'Save Profile')]"
    TRACK_TAXONOMY_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='3']//span)[1]"
    TRACK_TAXONOMY_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='3']//div//div//div//input)[1]"
    SELECT_TRACK_TAXONOMY = "//div[contains(text(),'401(k) Contributions | Line 1 | 401(k) Contributions | K1.L01.401(k) Contributions')]"
    NEGATIVE_TRACK_TAXONOMY_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//span)[1]"
    NEGATIVE_TRACK_TAXONOMY_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//div//div//div//input)[1]"
    SELECT_NEGATIVE_TRACK_TAXONOMY = "//div[contains(text(),'401(k) Contributions | Line 1 | 401(k) Contributions | K1.L01.401(k) Contributions')]"
    FEDERAL_TRACK_TAXONOMY_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//span)[1]"
    FEDERAL_TRACK_TAXONOMY_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='4']//div//div//div//input)[1]"
    SELECT_FEDERAL_TRACK_TAXONOMY = "//div[contains(text(),'401(k) Contributions | Line 1 | 401(k) Contributions | K1.L01.401(k) Contributions')]"
    FEDERAL_TRACK_TAXONOMY_NEGATIVE_MAPPING = "(//tr[@aria-rowindex='3']//td[@aria-colindex='5']//span)[1]"
    FEDERAL_TRACK_TAXONOMY_NEGATIVE_MAPPING_TYPE = "(//tr[@aria-rowindex='3']//td[@aria-colindex='5']//div//div//div//input)[1]"
    SELECT_FEDERAL_TRACK_TAXONOMY_NEGATIVE = "//div[contains(text(),'401(k) Contributions | Line 1 | 401(k) Contributions | K1.L01.401(k) Contributions')]"
    ALLOCABLE_ITEM_TEMPLATE_DROPDOWN = "(//input[@class='trux-input-select__input'])[1]"
    EDIT_ALLOCABLE_ITEM_TEMPLATE = "(//fa-icon[@truxtooltip='edit'])[1]"

}
export default AllocableItemTemplateLocators;