class DocumentTrackerLocators{

    DOCUMENT_CENTER = "//span[contains(text(),' Document Center ')]"
    DOCUMENT_TRACKER = "//a[contains(text(),' Document Tracker ')]"
    AFS_RECIEVED = "//td[@aria-label='Column AFS <br>Received']"
    APPROVED_FOR_PREP = "//td[@aria-label='Column Approved For <br>Return Prep']"
    FUND_RETURN_DELIVERED = "//td[@aria-label='Column Fund Return <br>Delivered']"
    TB_RECIEVED = "//td[@aria-label='Column TB <br>Received']"
    FUND_RETURN_DELIVERED_DATE = "//td[@aria-label='Column Fund Return <br>Delivered Date']"
    AFS_RECIEVED_DATE = "//td[@aria-label='Column AFS <br>Received Date']"
    APPROVED_FOR_RETURN_DATE = "//td[@aria-label='Column Approved For <br>Return Date']"
    TB_RECIEVED_DATE = "//td[@aria-label='Column TB <br>Received Date']"
    GEORGE_BLUTH_FUND = "//tr//td//div//a[contains(text(),' GEORGE BLUTH FUND')]"
    DETAIL_GRID = "//mezz-grid-wrapper[@class='document-tracker-detail-grid']"
    _1042S_RECIEVED = "//td[@aria-label='Column 1042s <br>Received?']"
    _1042S_RECIEVED_DATE = "//td[@aria-label='Column 1042s <br>Received Date']"
    _8805_RECIEVED = "//td[@aria-label='Column 8805 <br>Received?']"
    _8805_RECIEVED_DATE = "//td[@aria-label='Column 8805 <br>Received Date']"
    AGGREGATED_ENDING_CAPITAL = "//td[@aria-label='Column Aggregated <br>Ending Capital']"
    CAPITAL_RECIEVED = "//td[@aria-label='Column Capital <br>Received']"
    AGGREGATED_TAXABLE_INCOME = "//td[@aria-label='Column Aggregated <br>Taxable Income']"
    TAXABLE_INCOME_RECIEVED = "//td[@aria-label='Column Taxable <br>Income Received']"
    FUND = "//mezz-grid-wrapper//tr[@aria-rowindex='1']//td[@aria-colindex='1']"
    COLUMN_RECIEVED = "//td[@aria-label='Column Received']//div[contains(text(),'Received')]"
    COLUMN_CUTOFF_DATE = "//td[@aria-label='Column Cutoff Date']//div[contains(text(),'Cutoff Date')]"
    COLUMN_CHOOSER = "//input[@placeholder='Column chooser']"
    PRIMARY_ID = "//li//trux-checkbox//span[contains(text(),'Primary ID')]"
    TOTAL_NAV = "//li//trux-checkbox//span[contains(text(),' Total NAV')]"
    COLUMN_PRIMARY_ID = "//td[@aria-label='Column Primary ID']"
    COLUMN_TOTAL_NAV = "//td[@aria-label='Column Total NAV']"
    DOMESTIC_DROPDOWN = "//td[@aria-colindex='2']//div[@class='dx-dropdowneditor-icon']"
    DOMESTIC_VALUE = "//div[@class='dx-item-content dx-list-item-content' and contains(text(),'Domestic')]"
    CAPITAL_AMT = "//td[@aria-colindex='4']//input[@type='text']"
    CAPITAL_PERCENTAGE = "//td[@aria-colindex='5']//input[@type='text']"
    INCOME_AMT = "//td[@aria-colindex='6']//input[@type='text']"
    INCOME_PERCENTAGE = "//td[@aria-colindex='7']//input[@type='text']"
    RECIEVED_PER = "//td[@aria-colindex='9']//input[@type='text']"
    SAVE_SEARCH_BUTTON = "//span[contains(text(),'Save Search')]"
    FILTER_NAME_TEXTBOX = "//trux-slideout-body//input[@type='text']"
    SAVE_BTN = "//button//div[contains(text(),' Save ')]"
    RESET_GRID = "//span[contains(text(),'Reset Grid')]"
    SELECT_FILTER = "//div[@class='saved-search-list']//trux-input[@type='select']"
    SELECT_CORPORTATION = "//span[@class='saved-search-list__item--text']"
    INVESTOR_NAME = "//tr[@aria-rowindex='1']//td[@aria-colindex='1']//div//a"
    C2_VALUE = "//tr[@aria-rowindex='1']//td[@aria-colindex='2']"
    C3_VALUE = "//tr[@aria-rowindex='1']//td[@aria-colindex='3']"
    C4_VALUE = "//tr[@aria-rowindex='1']//td[@aria-colindex='4']"
    C5_VALUE = "//tr[@aria-rowindex='1']//td[@aria-colindex='5']"
    C6_VALUE = "//tr[@aria-rowindex='1']//td[@aria-colindex='6']"
    C7_VALUE = "//tr[@aria-rowindex='1']//td[@aria-colindex='7']"
    C9_VALUE = "//tr[@aria-rowindex='1']//td[@aria-colindex='9']"
    DELETE_BTN = "//li//fa-icon[@truxtooltip='Delete']"

}

export default DocumentTrackerLocators;