class DocumentCenterDocumentsLocators{
    DOCUMENT1_CHECKBOX = "//tr[@aria-rowindex='1']//div[@aria-label='Select row']"
    DOCUMENT2_CHECKBOX = "//tr[@aria-rowindex='2']//div[@aria-label='Select row']"
    ACTIONS_DROPDOWN = "//mezz-dropdown-button[@caption='Actions']//button"
    VIEW_SIDE_BY_SIDE = "//span[contains(text(),'View Side by Side')]"
    COMPARE_DOCUMENTS_SECTION = "//span[@class='mezz-breadcrumb__title'][contains(text(),' Compare Documents ')]"
    DOCUMENTS_COUNT_LABEL = "//label[contains(text(), 'Documents (2): ')]"
    SHOW_ZERO_VALUES_TOOGLE_BTN = "//div[@class='trux-switch__handler trux-switch__handler--normal']"
    RESET_GRID = "//span[contains(text(),'Reset Grid')]"
    DISPLAY_MATCHING_DUPLICATES_ICON = ".dx-datagrid-content-fixed > .dx-datagrid-table > tbody > [aria-rowindex='1'] > .dx-command-edit > .dx-template-wrapper > [truxtooltip='Display Matching Duplicates'] > .ng-fa-icon > .svg-inline--fa > path"
    ORIGINAL_DOCUMENT = "//tr[@aria-rowindex='1']//td[@aria-colindex='5']"
    APPROVED_DROPDOWN = "[aria-colindex='3'] > :nth-child(1) > .dx-editor-container > .dx-show-invalid-badge > .dx-dropdowneditor-input-wrapper > .dx-texteditor-container > .dx-texteditor-buttons-container > .dx-widget > .dx-button-content > .dx-dropdowneditor-icon"
    APPROVED_DROPDOWN_PENDING = "//div[@role='option']//div[contains(text(),'Pending')]"
    SELECT_ALL_CHECKBOX = "//div[@aria-label='Select all']"
    DELETE = "//button//span[contains(text(),'Delete')]"
    DELETE_YES = "//div[contains(text(),'Delete')]"
    EXPORT_ALL_DATA_BTN = ".export-masked-data-button__label"
    EXPORT_TO_TAX_DOCS = "//span[contains(text(),'Export to Tax Docs')]"
    APPROVED_DROPDOWN_APPROVED = "//div[@role='option']//div[contains(text(),'Approved')]"
    SCHEDULE_DROPDOWN = '.dx-datagrid-filter-row > [aria-colindex="9"]'
    CODE_DROPDOWN = "//tr[@aria-rowindex='1']//div[@class='dx-treelist-empty-space dx-treelist-collapsed']"
    VERIFY_VISIBILITY = "(//tbody[@role='presentation']//tr[@aria-rowindex='3']//td[@aria-colindex='2'])[1]"
    VERIFY_VISIBILITY_2 = "(//tbody[@role='presentation']//tr[@aria-rowindex='2']//td[@aria-colindex='1'])[1]"
    SUMMARY_DROPDOWN = "//h6[contains(text(),' Summary ')]"
    ALL_FOOTNOTES = "//span[@title='All Footnotes'][contains(text(),'All Footnotes')]"
    ALL_FOOTNOTES_VALUE = "//span[@automation-id='All Footnotes_value']"
    MISSING_FOOTNOTES = "//span[contains(text(),'Missing Footnotes')]"
    MISSING_FOOTNOTES_VALUE = "//span[@automation-id='Missing Footnotes_value']"
    UNEXPECTED_FOOTNOTES = "//span[contains(text(),'Unexpected Footnotes')]"
    UNEXPECTED_FOOTNOTES_VALUE = "//span[@automation-id='Unexpected Footnotes_value']"
    ECI = "//span[contains(text(),'ECI')]"
    ECI_VALUE = "//span[@automation-id='ECI_value']"
    UBTI = "//span[contains(text(),'UBTI')]"
    UBTI_VALUE = "//span[@automation-id='UBTI_value']"
    PASSIVE = "//span[contains(text(),'PASSIVE')]"
    PASSIVE_VALUE = "//span[@automation-id='PASSIVE_value']"
    FDAP = "//span[contains(text(),'FDAP')]"
    FDAP_VALUE = "//span[@automation-id='FDAP_value']"
    SSI_SSW = "//span[contains(text(),'SSI/SSW')]"
    SSI_SSW_VALUE = "//span[@automation-id='SSI/SSW_value']"
    INSTALL_SALES = "//span[contains(text(),'Install Sales')]"
    INSTALL_SALES_VALUE = "//span[@automation-id='Install Sales_value']"
    FORM_8886 = "//span[contains(text(),'8886')]"
    FORM_8886_VALUE = "//span[@automation-id='8886_value']"
    FORM_8865 = "//span[contains(text(),'8865')]"
    FORM_8865_VALUE = "//span[@automation-id='8865_value']"
    FORM_926 = "//span[contains(text(),'926')]"
    FORM_926_VALUE = "//span[@automation-id='926_value']"
    FORM_8621 = "//span[contains(text(),'8621 (PFICs)')]"
    FORM_8621_VALUE = "//span[@automation-id='8621 (PFICs)_value']"
    FORM_199A = "//span[contains(text(),'199A')]"
    FORM_199A_VALUE = "//span[@automation-id='199A_value']"
    EIP_TRANSFERS = "//span[contains(text(),'EIP - Transfers')]"
    EIP_TRANSFERS_VALUE = "//span[@automation-id='EIP - Transfers_value']"
    APPROVED_COLUMN = "//div[contains(text(),'Approved?') and @role='presentation']"
    SOURCE_COLUMN = "//div[contains(text(),'Source') and @role='presentation']"
    FILENAME_COLUMN = "//div[contains(text(),'File Name') and @role='presentation']"
    INVESTMENT_NAME_COLUMN = "//div[contains(text(),'Investment Name') and @role='presentation']"
    INVESTMENT_NAME_1 = "//tr[@aria-rowindex='1']//td[@aria-colindex='5']"
    INVESTMENT_NAME_2 = "//tr[@aria-rowindex='2']//td[@aria-colindex='5']"
    INVESTMENT_NAME_3 = "//tr[@aria-rowindex='3']//td[@aria-colindex='5']"
    INVESTMENT_NAME_4 = "//tr[@aria-rowindex='4']//td[@aria-colindex='5']"
    INVESTMENT_NAME_5 = "//tr[@aria-rowindex='5']//td[@aria-colindex='5']"
    DISABLED_DELETE_BUTTON = "//button[@class='trux-button__button trux-button__button--secondary trux-button__button--disabled trux-button__button--full-width']"
    SELECT_TAX_YEAR = "//trux-input[@placeholder='Select tax years']"
    TAX_YEAR = "//li[contains(text(),' 2023')]"

}
export default DocumentCenterDocumentsLocators;