
class ExpectedDocumentsEditsLocators {

    EXPECTED_DOCUMENTS = "//a[contains(text(),' Expected Documents ')]"
    ADD_EXPECTED_DOCUMENT = "//span[contains(text(),'Add Expected Document')]"
    EXPECTED_DOCUMENT_TAX_YEAR = "//trux-input[@formcontrolname='taxYear']"
    SCHEDULE_DROPDOWN = "//trux-input[@formcontrolname='scheduleId']"
    SCHEDULE_NAME = "//li[contains(text(),' Federal K-1')]"
    INVESTOR_DROPDOWN = "//trux-input[@formcontrolname='investorId']"
    SELECT_INVESTOR = "//li[contains(text(),' MADISON')]"
    SELECT_INVESTOR_2 = "//li[contains(text(),' 654 - PwC Entity')]"
    SELECT_INVESTOR_3 = "//li[contains(text(),' 1042 Intermediary 1')]"
    INVESTMENT_DROPDOWN = "//trux-input[@formcontrolname='investmentId']"
    SELECT_INVESTMENT = "//li[contains(text(),' MADISON')]"
    SELECT_INVESTMENT_2 = "//li[contains(text(),' 654 - PwC Entity')]"
    SELECT_INVESTMENT_3 = "//li[contains(text(),' 1042 Intermediary 1')]"
    ASSIGN_TO_TRACK_RADIO_BUTTON = "//label[@class='trux-radio']//span[contains(text(),' Investment ')]"
    IS_FOREIGN_DROPDOWN = "//trux-input[@formcontrolname='investmentEntityIsForeign']"
    SELECT_FOREIGN = "//li[contains(text(),' Foreign')]"
    CATEGORY_DROPDOWN = "//trux-input[@formcontrolname='category']"
    SELECT_CATEGORY = "//li[contains(text(),' Actual')]"
    SAVE_BUTTON = "//div[contains(text(),' Save ')]"
    CLOSE_SLIDEOUT_BUTTON = "//button[@class='trux-slideout-header__close-btn ng-star-inserted']"
    DOCUMENTS_TAB = "//a[@class='trux-tabs__tab-link trux-tabs__tab-link--first' and contains(text(),'Documents')]"
    MATCHED_DROPDOWN = "(//div[@class='dx-texteditor-buttons-container']//div[@role='button'])[2]"
    PAGE_LOADER = "//div[@class='dx-loadpanel-indicator dx-loadindicator dx-widget']"
    SELECT_UNMATCHED_DOCUMENTS_PAGE = "//div[contains(text(),'Unmatched')]"
    EDIT_UNMATCHED_DOCUMENT_ICON = "(//a[@truxtooltip='Edit'])[1]"
    EDIT_INVESTMENT_NAME = "//trux-input[@formcontrolname='investmentName']"
    EDIT_INVESTMENT_TAX_ID = "//trux-input[@formcontrolname='investmentTaxId']"
    COLUMN_CHOOSER = "//input[@placeholder='Column chooser']"
    SELECT_DOCUMENT_NAME_COLUMN = "//span[@class='trux-checkbox__label' and contains(text(),' Document Name')]"
    PAGE_CLICK = "//div[@class='document-grid-container']"
    EDIT_DOCUMENT_NAME = "//trux-input[@formcontrolname='alternateName']"
    SEARCH_FILE_NAME = "(//td[@aria-colindex='5']//following::input[@class='dx-texteditor-input'])[3]"
    EDIT_INVESTOR_NAME = "//trux-input[@formcontrolname='investorName']"
    EDIT_INVESTOR_ID = "//trux-input[@formcontrolname='investorTaxId']"
    CLOSE_SLIDEOUT = "//button[@aria-label='Close slideout']"
    VERIFY_UNMATCHED_INVESTMENT_NAME = "//td[contains(text(),'Testing Unmatched Investment')]"
    VERIFY_UNMATCHED_DOCUMENT_NAME = "//td[contains(text(),'First')]"
    SELECT_MATCHED_DOCUMENTS_PAGE = "(//div[contains(text(),'Matched')])[2]"
    VERIFY_MATCHED_INVESTMENT_NAME = "//td[contains(text(),'Testing Matched Investment')]"
    VERIFY_MATCHED_DOCUMENT_NAME = "//td[contains(text(),'Match')]"
    RESET_GRID = "//span[contains(text(),'Reset Grid')]"
    DIRECT_CONNECT_TOGGLE_BUTTON = "(//span[@truxtogglelabel='off'])[2]"
    TRACK_PROFILE_DROPDOWN = "//trux-input[@formcontrolname='trackProfileId']"
    SELECT_TRACK_PROFILE = "//li[contains(text(),' BennyTam-QA -2023-BennyTest2023_FER')]"
    SELECT_TRACK_PROFILE_2 = "//li[contains(text(),' BennyTam-QA -2023-BennyTest2023_FTFUAT')]"
    ALLOCABLE_ITEM_MAPPING_DROPDOWN = "//trux-input[@formcontrolname='taxonomyTemplateId']"
    SELECT_ALLOCABLE_ITEM_MAPPING = "//li[contains(text(),' Tax Year: 2023 - Latest Template')]"
    SELECT_ALLOCABLE_ITEM_MAPPING_2 = "//li[contains(text(),' Tax Year: 2023 - Big Template')]"


}
export default ExpectedDocumentsEditsLocators;