class ProcessingLocators {
    EXISTING_ENGAGEMENT = "//div[contains(text(),'DATAFLOW_QA_AUTOMATION')]";
    UPLOAD_FILES = "//span[contains(text(),'Upload Files')]"
    UPLOAD_FILES_BUTTON = "//awm-button[@btntype='primary']"
    UPLOAD_FILES_AREA = "//awm-slideout//input[@type='file']"
    CLOSE_UPLOAD_FILES_SLIDEOUT = "//upload-slideout-container//awm-slideout//div//awm-icon//span[@class='awm-icon Appkit4-icon icon-close-outline ap-font-16']"
    DOCUMENT_CENTER = "//span[contains(text(),'Document Center')]"
    EXECUTIVE_REVIEW = "//a[contains(text(),'Executive Review')]"
    REVIEW_ICON = "//a[@class='review-link']"
    UPLOADED_FILE_NAME = "//span[@class='ap-fileupload-fileName']"
    PROCESS_STATUS_INDICATOR_1 = "//div[@aria-rowindex='3']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_2 = "//div[@aria-rowindex='4']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_3 = "//div[@aria-rowindex='5']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_4 = "//div[@aria-rowindex='6']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_5 = "//div[@aria-rowindex='7']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_6 = "//div[@aria-rowindex='8']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_7 = "//div[@aria-rowindex='9']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_8 = "//div[@aria-rowindex='10']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_9 = "//div[@aria-rowindex='11']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_10 = "//div[@aria-rowindex='12']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_11 = "//div[@aria-rowindex='13']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    PROCESS_STATUS_INDICATOR_12 = "//div[@aria-rowindex='14']//div[@aria-colindex='3']//span[@class='processing-status-indicator']//span"
    EXPAND_FILE_DETAILS = "//tr[@aria-rowindex='1']//div[@class='dx-datagrid-group-closed']"
    COLAPSE_FILE_DETAILS = ".dx-datagrid-group-opened"
    DOC_1 = "//tr[@aria-rowindex='1']//td[@aria-colindex='2']"
    DOC_2 = "//tr[@aria-rowindex='2']//td[@aria-colindex='2']"
    DOC_3 = "//tr[@aria-rowindex='3']//td[@aria-colindex='2']"
    DOC_4 = "//tr[@aria-rowindex='4']//td[@aria-colindex='2']"
    DOC_5 = "//tr[@aria-rowindex='5']//td[@aria-colindex='2']"
    DOC_6 = "//tr[@aria-rowindex='6']//td[@aria-colindex='2']"
    DOC_7 = "//tr[@aria-rowindex='7']//td[@aria-colindex='2']"
    DOC_8 = "//tr[@aria-rowindex='8']//td[@aria-colindex='2']"
    DOC_9 = "//tr[@aria-rowindex='9']//td[@aria-colindex='2']"
    DOC_10 = "//tr[@aria-rowindex='10']//td[@aria-colindex='2']"
    DOC_11 = "//tr[@aria-rowindex='11']//td[@aria-colindex='2']"
    DOC_12 = "//tr[@aria-rowindex='12']//td[@aria-colindex='2']"
    PROCESSING_DOCS = "(//span[@class='tile-body-documents-title'])[2]"
    UPLOAD_WIDGET = "//trux-file-upload//input[@type='file']"
    ERROR_NOTIFICATION = "//div[@class='trux-notification__content']"
    FLOATING_WINDOW = "//div[@class='mezz-file-upload-floating-window__body']"
    SEARCH_MESSAGE = "//td[@aria-colindex='4']//input"
    CONTACT_SUPPORT = "//tr[@aria-rowindex='1']//a[contains(text(),'contact support')]"
    ERROR_MESSAGE = "//div[@class='ap-fileupload-error-message ng-star-inserted']"
    SLIDEOUT_ENTER_PASSWORD = "//awm-slideout//span[contains(text(),'enter password')]"
    PASSWORD_TEXTBOX = "//input[@type='password']"
    ENTER = "//button//div[contains(text(),'Enter')]"
    GRID_ENTER_PASSWORD = "//div[@aria-rowindex='3']//span[contains(text(),'enter password')]"
    SUCCESS_CIRCLE = "//span[@class='ap-fileupload-success ng-star-inserted']"
    PDF_STATUS = "//div[@aria-rowindex='3']//div[@aria-colindex='3']//span[@class='processing-status-indicator__text--default']"
}
export default ProcessingLocators;