class SecAuthLocators{
ADMIN = "//span[contains(text(),'Admin')]"
SECURITY_AUTHORIZATION = "//div[contains(text(),' Security Authorization ')]"
USER_GRID = "//div[@class='users-grid']"
GUID_SEARCH_TEXTBOX = "//td[@aria-colindex='2']//input[@type='text']"
EDIT_ICON = "//mezz-edit-action-icon//a[@class='action-icon']"
SAVE_BTN = "//div[contains(text(),' Save ')]"
ENGAGEMENT_ACCESS = "//a[contains(text(),' Engagement Access ')]"
ADD_ENGAGEMENT_ACCESS = "//button[contains(text(),' Add Engagement Access ')]"
PERMISSIONS = "//a[contains(text(),' Permissions ')]"
ADD_PERMISSIONS = "//button[contains(text(),' Add another Permission ')]"
HEADER_SECURITY_AUTHORIZATION = "//h6[contains(text(),'Security Authorization')]"
SEARCH_GUID_TEXTBOX = "//td[@aria-colindex='2']//input[@type='text']"
EDIT_USER = "//span[@class='awm-icon Appkit4-icon icon-pencil-fill ap-font-16']"
USERNAME = "//trux-input[@formcontrolname='userName']//trux-input-accent"
FIRST_NAME = "//trux-input[@formcontrolname='firstName']//input[@type='text']"
LAST_NAME = "//trux-input[@formcontrolname='lastName']//input[@type='text']"
EMAIL = "//trux-input[@formcontrolname='email']//input[@type='text']"
SELECT = "//trux-input[@type='select']"
SEARCH_ENGAGEMENT = "//input[@placeholder='Search...']"
DATAFLOW_QA_AUTOMATION = "//li[contains(text(),' QA Testing, DATAFLOW_QA_AUTOMATION')]"
ENGAGEMENT_ADMIN = "//li[contains(text(),' Engagement Admin')]"
ONE_DAY = "//li[contains(text(),' One Day')]"
EDIT_ENGAGEMENT_ACCESS_ICON = "//fa-icon[@class='ng-fa-icon form-list__icon']"
ENGAGEMENT_USER_OPTION = "//li[contains(text(),' Engagement User')]"
ONE_YEAR_OPTION = "//li[contains(text(),' One Year')]"
REMOVE ="//div[contains(text(),' Remove ')]"
DATAFLOW_OPTION ="//li[contains(text(),' Dataflow')]"
STAR_OPTION = "//li[contains(text(),' *')]"
ONE_DAY_PERMISSION = "//span[contains(text(),' One Day ')]"
BE_OPTION = "//li[contains(text(),' BusinessEntity')]"
CAN_VIEW_OPTION = "//li[contains(text(),' CanView')]"
}
export default SecAuthLocators;