class StateSourceGridLocators{
SEARCH_DOC = "//td[@aria-colindex='5']//input[@type='text']"
MATCH_ICON = "//tr[@aria-rowindex='1']//td[@aria-colindex='2']//a[@truxtooltip='Match']"
EXP_DOC_ID = "//trux-input[@formcontrolname='expectedDocumentId']//input"
EXP_TEXT_BOX = "//trux-list-search//input[@type='text']"
EXP_OPTION = "//li//span[contains(text(),' Federal K-1 (2023) Corporation - Corporation ')]"
MATCH_BTN = "//button//div[contains(text(),' Match ')]"
REVIEW_ICON = "//tr[@aria-rowindex='1']//td[@aria-colindex='2']//a[@awmtooltip='Review']"
SELECT_DROPDOWN = "//trux-input[@class='review-toolbar__view-by-input trux-input-select']//input[@placeholder='Select...']"
STATE_SOURCE = "//li[contains(text(),' State Source - Fed to State Comparison')]"
COLOUMN_DROPDOWN = "//mezz-input-dropdown-tree-view[@multipleselectedtext='Columns selected']"
STATE_ADJUSTMENT = "//li[@data-item-id='State%20Adjustments']"
APPORTIONMENT = "//li[@data-item-id='Apportionment']"
PAYMENTS = "//li[@data-item-id='Payments']"
TRACK_REVIEW_BUTTON = "//div[@class='state-source-toolbar']//div[@class='trux-button__content']"
READY_FOR_TRACK_REVIEW = "//div[contains(text(),' Ready for TRACK review ')]"
NOTIFICATION = "//div[@class='mezz-notification__body']//span"
OK = "//div[contains(text(),' Ok ')]"
EDIT_ALLOCABLE_ITEMS = "//div[contains(text(),' Edit Allocable Items ')]"
NOTIFICATION_CONTENT = '.trux-notification__content'
TAXONOMY_ROW = "//span[contains(text(),'Taxonomy')]"
SELECT_PROFILE = "//trux-input[@type='select']"
PROFILE_OPTION = "//li[contains(text(),' BennyTam-QA -2021-BennyTest2021')]"
DOC_FOR_REVIEW = "//td[contains(text(), '2023 3-MADISON_1_22.pdf')]"
REVIEW_ALLOCABLE_ITEMS = "//span[contains(text(),'Review Allocable Items')]"
STATE = "//a[contains(text(), 'State')]"
AMOUNT_1 = "//div[@aria-rowindex='3']//div[@aria-colindex='4' and @col-id='amount']"
AMOUNT_2 = "//div[@aria-rowindex='4']//div[@aria-colindex='4' and @col-id='amount']"
AMOUNT_3 = "//div[@aria-rowindex='5']//div[@aria-colindex='4' and @col-id='amount']"
AMOUNT_4 = "//div[@aria-rowindex='6']//div[@aria-colindex='4' and @col-id='amount']"
AMOUNT_5 = "//div[@aria-rowindex='7']//div[@aria-colindex='4' and @col-id='amount']"
AMOUNT_6 = "//div[@aria-rowindex='8']//div[@aria-colindex='4' and @col-id='amount']"
AMOUNT_7 = "//div[@aria-rowindex='9']//div[@aria-colindex='4' and @col-id='amount']"
AMOUNT_8 = "//div[@aria-rowindex='10']//div[@aria-colindex='4' and @col-id='amount']"
SEND_TO_TRACK = "//span[contains(text(),'Send to TRACK')]"
TRACK_ALLOCABLE_ITEMS = "//li[contains(text(),' TRACK Allocable Items')]"
REAPPLY_TEMPLATE = "//div[contains(text(),' Reapply Template ')]"
REAPPLY = "//trux-notification//div[contains(text(),' Reapply ')]"
MATCH_SPAN = "//span[contains(text(),'Match')]"
EXP_OPTION_2 = "//li//span[contains(text(),' Federal K-1 (2023) GEORGE BLUTH FUND - GEORGE BLUTH FUND ')]"
DOC_CENTER = "//mezz-sidebar-item//span[contains(text(),'Document Center')]"
CHECKNOX = "//tr[@aria-rowindex='1']//span[@class='dx-checkbox-icon']"
ACTIONS_DROPDOWN = "//div[contains(text(),' Actions ')]"
UNMATCH_OPTION = "//trux-button//span[contains(text(),'Unmatch')]"
UNMATCH = "//div[contains(text(),' Unmatch ')]"
MORE = "//div[@truxtooltip='More']"
EDIT_META_DATA = "//span[contains(text(),'Edit Metadata')]"
INVESTMENT_ID = "//trux-input[@formcontrolname='investmentId']"
I_ID_OPTION = "//li[contains(text(),' GEORGE BLUTH FUND')]"
INVESTOR_ID = "//trux-input[@formcontrolname='investorId']"
SAVE = "//div[contains(text(),' Save ')]"
CONFIRM = "//div[contains(text(),' Confirm ')]"
DELETE_OPTION = "//trux-button//span[contains(text(),'Delete')]"
DELETE = "//div[contains(text(),' Delete ')]"
UPPER_TIER_1 = "//td[@aria-colindex='11']//input[@type='text']"
ARIZONA = "//tr[@aria-rowindex='3']//td[@aria-colindex='1']//div[@class='dx-treelist-icon-container']"
C_1 = "(//div[contains(text(),' (50) ')])[1]"
C_2 = "(//tr[@aria-rowindex='3']//td[@aria-colindex='2'])[1]"
C_2_TEXT = "//tr[@aria-rowindex='3']//td[@aria-colindex='2']//input"
C_3 = "//tr[@aria-rowindex='4']//td[@aria-colindex='1']"
EDITED_VALUE = "(//div[contains(text(),' (1999) ')])[1]"
C_4 = "//tr[@aria-rowindex='4']//td[@aria-colindex='2']"
}

export default StateSourceGridLocators;