
class UploadFileRedesignLocators {

    UPLOAD_BUTTON = "//button[@class='ap-button ap-button-primary ng-star-inserted']//div[contains(text(),' Upload')]"
    UPLOAD_SLIDEOUT_BODY = "//div[@class='file-upload-container__blurb']"
    CHOOSE_FILES_TO_UPLOAD = "//awm-slideout//input[@type='file']"
    VERIFY_UPLOADED_ICON = "//span[@class='Appkit4-icon icon-circle-checkmark-outline']"
    VERIFY_UPLOADED_ERROR_MSG = "//div[@class='ap-fileupload-error-message ng-star-inserted']"
    CLOSE_UPLOAD_SLIDEOUT = "//span[@class='awm-icon Appkit4-icon icon-close-outline ap-font-16']"
    UPLOAD_FILE_SPINNER = "//div[@class='inside-circle']"
    UPLOADED_FILE_COUNT = "//div[@class='file-upload-container__counter ng-star-inserted']"
    ALL_DOCUMENTS_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-documents'])[1]"
    ALL_DOCUMENTS_FILES_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-files'])[1]"
    ALL_PROCESSING_DOCS_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-documents'])[2]"
    ALL_PROCESSING_FILES_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-files'])[2]"
    FILE_PROCESSING_QUEUE = "//div[contains(text(),' Go to file processing queue ')]"
    SUCCESS_DOCUMENTS_FILES_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-files'])[3]"
    ALL_SUCCESS_DOCUMENTS_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-documents'])[3]"
    DELETED_DOCUMENTS_FILES_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-files'])[5]"
    ALL_DELETED_DOCUMENTS_COUNT = "(//div[@class='upload-tiles-container__row-tile-body-documents'])[5]"
    DOCUMENT_CENTER = "//span[contains(text(),' Document Center ')]"
    FILE_NAME_SEARCHBOX = "//td[@aria-colindex='5']//input[@type='text']"
    SELECT_CHECKBOX_DOC_CENTER = "//tr[@aria-rowindex='1']//td[@aria-colindex='1']//div//span"
    ACTIONS_BUTTON = "//div[contains(text(),' Actions ')]"
    DELETE_BUTTON = "//span[contains(text(),'Delete')]"
    POPUP_DELETE_BUTTON = "//div[contains(text(),' Delete ')]"
    RESET_GRID = "//span[contains(text(),'Reset Grid')]"
    CURRENT_YEAR_BUTTON = "//span[@class='ap-tabset-toggle-active']//span[contains(text(),'Current Year')]"
    LAST_TWO_YEARS_BUTTON = "//span[@class='ap-tabset-toggle-active']//span[contains(text(),'Last Two Years')]"
    CUSTOM_DATE_RANGE_BUTTON = "//span[@aria-label='Choose date']"
    COLUMN_CHOOSER_BUTTON = "//span[@class='awm-icon Appkit4-icon icon-container-outline ap-font-16']"
    EXPORT_TO_EXCEL = "//span[@class='awm-icon Appkit4-icon icon-download-light-outline ap-font-16']"
    PROCESSING_FILE_SPINNER = "//div[@class='inside-circle']"
    SEARCH_FILE_NAME = "//td[@aria-colindex='2']//input"
    UPLOADED_FILE_DROPDOWN = "(//div[@class='dx-datagrid-group-closed'])[1]"
    TAX_YEAR_NAME = "//td[@aria-label='Column Tax year']"
    VERIFY_TAX_YEAR = "(//td[contains(text(),'2023')])[1]"
    UPLOADED_FILE_FLOATING_PANEL = "//div[@class='mezz-file-upload-floating-window mezz-file-upload-floating-window--expanded ng-star-inserted']"
    UPLOADED_FILE_NAME = "//span[@class='ap-fileupload-fileName']"
    FLOATING_PANEL_HEADER = "//div[@class='mezz-file-upload-floating-window__header']"
    FLOATING_PANEL_CLOSE_BUTTON = "//span[@class='awm-icon Appkit4-icon icon-close-outline ap-font-16']"

}
export default UploadFileRedesignLocators